# .github/workflows/scheduled-builds.yml
name: Check CGE appointments

on:
  schedule:
    # https://crontab.guru
    - cron: "10,40 10-23 * * *"
jobs:
  build:
    name: Check new appointments date
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        run: yarn install
      - name: Run script
        run: yarn start
        env:
          BOT_KEY: ${{ secrets.BOT_KEY }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          PROXIMA_APERTURA: ${{ vars.PROXIMA_APERTURA }}
