# .github/workflows/scheduled-builds.yml
name: Check CGE appointments

on:
  schedule:
    # https://crontab.guru
    - cron: "45,50 * * * *"
jobs:
  build:
    name: Check new appointments date
    runs-on: ubuntu-latest
    steps:
      - name: Run script
        run: yarn start
        env:
          BOT_KEY: ${{ secrets.BOT_KEY }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
